### PR TITLE
vde_switch consistent program path

### PR DESCRIPTION
**Pull request by flyinprogrammer**
i believe these were missed in this commit: https://github.com/lima-vm/vde_vmnet/commit/b3c2d6ad8e2508db5b80a4ce04b161f006d34b72

maybe? while trying to troubleshoot why these services won't start on my machine it seemed like a minor thing to fix 🤷

### CODE REVIEW

**Comment by jandubois** [comment]
> i believe these were missed in this commit: [b3c2d6a](https://github.com/lima-vm/vde_vmnet/commit/b3c2d6ad8e2508db5b80a4ce04b161f006d34b72)

I think they were rather re-introduced in 55799ca, but anyways, good catch!

**Review by jandubois — APPROVED** [review]
Thank you, LGTM!

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by AkihiroSuda** [comment]
(Why didn't we catch this in CI?)

**Comment by jandubois** [comment]
> (Why didn't we catch this in CI?)

Not sure. But probably because we do `brew install qemu`, which depends on the `vde` package, which will install `/usr/local/bin/vde_switch`. That means the launch daemon may have been failing initially but can now restart successfully and the following test succeeds.

Which means the CI test would have been running against the homebrew version of `vde_switch` and not against the one we built and installed.

Not 100% sure this is what happened, but seems plausible to me.

**Pull request merged**
